name: Deploy App to Firebase

on:
  push:
    branches: [ "master" ]

jobs:
  Deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.SECRET_TOKEN }}
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run tests
      run: ./gradlew test

    - name: Build and Deploy Debug
      run: ./gradlew assembleDebug appDistributionUploadDebug
      env: 
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
