name: Publish Release APK

on:
  push:
    branches: [ "master" ]
    tags:
      - '*'

jobs:
  Gradle:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Run tests
        run: ./gradlew test

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Releasing using Hub
        uses: VladDaniliuk/action-release-releaseapk@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          VERSION_VARIABLE: versionName
          APP_FILE: buildSrc/Android.kt
          APP_FOLDER: ./app/release/app.apk
          CHANGELOG_FILE: ./CHANGELOG.md
          RELEASE_TITLE: New Build
          NAME_VARIABLE: app-release.apk