name: Release new apk to github

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    tags:
      - '*'

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease



      - name: Build Android release APK with EXPO
        uses: goblin-ihx/action-release-releaseapk@v2
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
          APP_FOLDER: app