name: Release new apk to github

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    tags:
      - '*'

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Print current directory again
        run: pwd

      - name: List files in the current directory
        run: ls -la

      - name: Verify git status
        run: git status

      - name: Add and commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Commit changes made during build process"

      - name: Releasing using Hub
        uses: kyze8439690/action-release-releaseapk@master
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
          APP_FOLDER: app