name: Release new apk

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SECRET_TOKEN }}

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Find APK file
        id: find_apk
        run: echo "::set-output name=apk_path::$(find app/build/outputs/apk/release -name "*.apk" | head -n 1)"

      - name: Get the latest tag
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1` 2>/dev/null || echo "v0.0.0")
          echo "Latest tag: $latest_tag"
          echo "::set-output name=latest_tag::$latest_tag"

      - name: Increment tag
        id: increment_tag
        run: |
          latest_tag=${{ steps.get_latest_tag.outputs.latest_tag }}
          IFS='.' read -r -a version_parts <<< "${latest_tag#v}"
          major=${version_parts[0]}
          minor=${version_parts[1]}
          patch=${version_parts[2]}
          new_patch=$((patch + 1))
          new_tag="v$major.$minor.$new_patch"
          
          while git rev-parse "refs/tags/$new_tag" >/dev/null 2>&1; do
            new_patch=$((new_patch + 1))
            new_tag="v$major.$minor.$new_patch"
          done
          
          echo "New tag: $new_tag"
          echo "::set-output name=new_tag::$new_tag"

      - name: Delete existing tag and release if they exist
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
        run: |
          new_tag=${{ steps.increment_tag.outputs.new_tag }}
          if git rev-parse "refs/tags/$new_tag" >/dev/null 2>&1; then
            git tag -d "$new_tag"
            git push --delete origin "$new_tag"
          fi
          
          release_id=$(curl -s \
            -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/releases/tags/$new_tag \
            | jq -r '.id')
          
          if [ "$release_id" != "null" ]; then
            curl -s \
              -X DELETE \
              -H "Authorization: token $GITHUB_TOKEN" \
              https://api.github.com/repos/${{ github.repository }}/releases/$release_id
          fi

      - name: Create new tag
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          new_tag=${{ steps.increment_tag.outputs.new_tag }}
          git tag "$new_tag"
          git push origin "$new_tag"

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ steps.find_apk.outputs.apk_path }}"
          tag: ${{ steps.increment_tag.outputs.new_tag }}
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}"