name: Publish Release APK

on:
  push:
    branches: [ "master" ]
    tags:
      - '*'

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4.1.7

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Run tests
        run: ./gradlew test

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Releasing using Hub
        uses: kyze8439690/action-release-releaseapk@master
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
          APP_FOLDER: app