name: Release new apk to github

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    tags:
      - '*'

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Releasing using Hub
        uses: VladDaniliuk/action-release-releaseapk@master
        env:
          JAVA_HOME: /opt/hostedtoolcache/Java_Zulu_jdk/17.0.11-9/x64
          JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Zulu_jdk/17.0.11-9/x64
          GRADLE_BUILD_ACTION_SETUP_COMPLETED: true
          GRADLE_BUILD_ACTION_CACHE_RESTORED: true
          DEVELOCITY_INJECTION_INIT_SCRIPT_NAME: gradle-actions.inject-develocity.init.gradle
          DEVELOCITY_AUTO_INJECTION_CUSTOM_VALUE: gradle-actions
          GITHUB_DEPENDENCY_GRAPH_ENABLED: false
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
          VERSION_VARIABLE: versionName
          APP_FILE: app/build.gradle.kts
          APP_FOLDER: app/build/outputs/apk/debug/app-debug.apk
          CHANGELOG_FILE: .github/workflows/CHANGELOG.md
          RELEASE_TITLE: New Version
          NAME_VARIABLE: MyCamera Translator.apk